LRDOCS 7844 liferay workspace
sez11a/liferay-learn pull request #439
Opened 2021-04-29 18:13 UTC by sez11a

2021-04-29 19:20 UTC, lawrence-lee commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-liferay-workspace.md
> +   ```groovy
Depending on the version of workspace you are upgrading to or from, you might need to update your gradle wrapper first. Please refer to the gradle-plugins-workspace change log to determine which gradle wrapper version is best.

2021-04-29 21:48 UTC, gamerson requested changes
Great work @sez11a  and Cody, appreciate the efforts to document everything!

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/blade-cli/generating-projects-with-blade-cli.md
> +blade create -t mvc-portlet -p com.acme.z3x1.portlet -c GuestbookPortlet -v 7.4 guestbook
99% of the time you do not need to add the `-v` flag.  Blade determines the correct version by looking at the enclosing workspace.  The only time that you would want to specify the `-v` flag if you want to deviate from the version of liferay that the workspace is configured for.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/blade-cli/generating-projects-with-blade-cli.md
> +This creates a project using the MVC Portlet template, a default package called `com.acme.z3x1.portlet`, a portlet class called `GuestbookPortlet`, for Liferay 7.4, called *guestbook*. Liferay Worksp
The line about `liferay workspaces can be imported..` should likely be added to the previous paragraphs introducing Liferay workspaces.  You could add a note here that once you have imported a workspace into your IDE, and if later on you add a new project, you will need to "refresh" your gradle project in your IDE.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/developer-tools-overview.md
> +[**Liferay Workspace**](./liferay-workspace/what-is-liferay-workspace.md) is a Gradle-based environment that holds your projects and their configurations. You can deploy to Liferay DXP, create and st
We sorta describe Liferay workspace differently in a different part of this pull request.  Should those be two descriptions be normalized or made the same?

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/developer-tools-overview.md
> +[**Blade CLI**](./blade-cli/installing-and-updating-blade-cli.md) makes it easy to create and build both standalone projects and Liferay Workspaces from your command line interface. Experienced devel
Blade CLI no longer really supports standalone projects.   It can still create standalone projects, but they wont work out of the box.  They all require changes to make them compile.  Alll blade templates assume a surrounding workspace scaffolding.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-a-liferay-docker-container.md
> +1. Specify the Docker tag using the property `liferay.workspace.docker.image.liferay`. Here are some examples:
We should somehow mention that most people will not set the docker.image.liferay but instead will be using it from liferay.workspace.product, so maybe that can be mentioned.  That the product key comes with a default docker image and they can use this property if they want to "override" what is in the product key.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-a-liferay-docker-container.md
> +A Docker image based on the name of your workspace with `-liferay` appended is created. For example, if your workspace folder was `my-project`, your Docker container is called `my-project-liferay`. Y
The "docker image id" can be customized if they don't like the `-liferay` suffix.  Same with the container id.  But its very good that we document the "default" values since useres will need to know the ids to look up in the docker registry.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-liferay-workspace.md
> +STOP! Liferay Workspace is simple to use, and you can learn the basics by starting [at the beginning](./what-is-liferay-workspace.md). If you're happily [creating projects](./creating-code.md), [depl
👍

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-liferay-workspace.md
> +But what if you need a new feature in the [Source Formatter plugin](https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.source.formatter/) or ano
I'm not sure if SF plugin is the best example of a plugin that users may want to configure specifically.  CSS Builder or ServiceBuilder.  And these only are for the "builder" style plugins.  not all gradle plugins will work this way, like target-platform plugin or test-integration plugin.  Frankly I think we could remove this all together.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/creating-a-liferay-workspace.md
> +    gradle wrapper --gradle-version 5.6.4
Use 6.6.1 since that is the new default.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/creating-a-liferay-workspace.md
> +   blade init -v 7.3 [workspace name]
the value specified after the `-v` should be one of the versions listed in the `blade init -l`.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/creating-code.md
> +   yo liferay-theme
We also have support for this in blade
`blade create -t js-theme` if you wanted to document that.  Because this `js-theme` will download nodejs and yo in the background and excutes 'yo liferay-theme' automatically.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/creating-code.md
> +   **CE:** Browse [releases-cdn.liferay.com](https://releases-cdn.liferay.com), find the bundle you need, and copy its URL to your clipboard.
Should we use this URL? https://releases-cdn.liferay.com/portal/

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/creating-code.md
> +../gradlew deployDocker
No need to call this directly.  `gw deploy` automtically calls `gw deployDocker`. Users dn't need to know about `deployDocker` they can just always do `gw deploy`. that will do everything they need.

2021-04-29 21:48 UTC, gamerson commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/what-is-liferay-workspace.md
> +Liferay Workspace is a set of folders and Gradle scripts that represents the Liferay-opinionated way of handling a full development life cycle:
a 3rd description of workspace :) which one is correct? 😸

2021-05-06 21:48 UTC, sez11a commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-liferay-workspace.md
> +   ```groovy
@lawrence-lee the only mentions of Gradle Wrapper I can find there are from 2016, unless I'm looking in the wrong place: 

https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-workspace/CHANGELOG.markdown

2021-05-06 21:58 UTC, sez11a commented on docs/dxp/latest/en/developing-applications/tooling/developer-tools-overview.md
> +[**Liferay Workspace**](./liferay-workspace/what-is-liferay-workspace.md) is a Gradle-based environment that holds your projects and their configurations. You can deploy to Liferay DXP, create and st
It'll become clear once this is published, but this is the intro article, where I summarize generally what is explained in detail later.

2021-05-06 22:29 UTC, sez11a commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-a-liferay-docker-container.md
> +A Docker image based on the name of your workspace with `-liferay` appended is created. For example, if your workspace folder was `my-project`, your Docker container is called `my-project-liferay`. Y
Since you're out, I'm going to create a ticket for this one, as I have a question: is that a property? Is the property `docker.image.id`? How do I get a list of all possible properties? 

https://issues.liferay.com/browse/LRDOCS-9428

2021-05-06 22:32 UTC, sez11a commented on docs/dxp/latest/en/developing-applications/tooling/liferay-workspace/configuring-liferay-workspace.md
> +But what if you need a new feature in the [Source Formatter plugin](https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.source.formatter/) or ano
Removed. It seemed rather hacky to me anyway, but it was there in previous versions, so I ported it. :-p

2021-05-06 22:44 UTC, sez11a commented
Superseded by https://github.com/brianchandotcom/liferay-learn/pull/195

2021-05-06 22:44 UTC, closed without merging